### ISSUE TITLE
Filters are applied twice

### ISSUE THREAD

**Issue by danizord** [guzzle/guzzle-services#134]
I have the following query param:
```php
'load_relations' => [
    'location' => 'query',
    'type'     => 'string',
    'required' => false,
    'filters'  => ['json_encode'],
],
```

So, when I call `$client->getCustomers(['load_relations' => ['Contact']);` I'd expect Guzzle to send a request with the following query string: `?load_relations=%5B%22Contact%22%5D`.
But instead I got: `?load_relations=%22%5B%5C%22Contact%5C%22%5D%22`.

That's because Guzzle is filtering the value with `json_encode` twice:
1 - https://github.com/guzzle/guzzle-services/blob/1.1.0/src/Handler/ValidatedDescriptionHandler.php#L47
2- https://github.com/guzzle/guzzle-services/blob/1.1.0/src/RequestLocation/AbstractLocation.php#L65

**Comment by Nader-Zubaid** [comment]
reply+0187cec5533e4c464be0a26d0deed8454cb8cf6aa248b53c92cf0000000115673d7e92a169ce0dcbb4e1@reply.github.com

**Comment by oliverde8** [comment]
Hi, 

This issue is still present in the 1.1.2 release, 

```json
"startDate": {
          "description": "creation date for filtering. Format: 'yyyy-MM-dd'T'HH:mm:ss'",
          "location": "query",
          "sentAs": "start_date",
          "filters" : [
            {
              "method": "date_format",
              "args" : ["@value", "Y-m-d\\TH:i:s\\Z"]
            }
          ]
        },
```

This will crash because in the `ValidationDescriptionHandler` the filtering is already done, and later on, the filtering is done again by the `Parameters->filter` 

which caused the fallowing issue 
```
Warning: date_format() expects parameter 1 to be DateTimeInterface, string given  
```

I am not sure I understand why filtering is done at all at the validation step. Originally my parameter description was :

```yml
        "startDate": {
          "type": "object",
          "instanceOf" : "DateTime",
          "description": "creation date for filtering. Format: 'yyyy-MM-dd'T'HH:mm:ss'",
          "location": "query",
          "sentAs": "start_date",
          "filters" : [
            {
              "method": "date_format",
              "args" : ["@value", "Y-m-d\\TH:i:s\\Z"]
            }
          ]
        },
```
But this creates another error because the filtering is done before the check and therefore I don't have a \DateTime anymore`

**Comment by danizord** [comment]
Hey @oliverde8, this issue was reintroduced since my PR #135 got reverted by https://github.com/guzzle/guzzle-services/commit/65ded511e534f98fa3abe4471a28ab7317237cf4. It seems like https://github.com/guzzle/guzzle-services/issues/145 relies on this behavior :/

**Comment by Konafets** [comment]
Hi, 

the removal introduced a regression or as @danizord mentioned, some folks rely on the odd behavior. I plan to work on that issue and other stuff regarding this package in September again. Stay tuned or provide a PR which takes both issues into account and comes with proper tests :-)

**Comment by oliverde8** [comment]
Hi, 

I will be using 1.1.1 for now as I have limited time on this part of the application and need to finish everything by mid September. I basically upgraded a library that was using guzzle 4 but couldn't use as it is due to other dependencies requiring guzzle 6.  

If i have any time I will look into it for a PR, but I don't think I will have time, 

Thanks for you support

**Comment by tlorens** [comment]
You can just create your own location class that implements AbstractLocation and override the functions that are calling the filters again.
